repos:
-   repo: local
    hooks:
    -   id: update-secrets-template
        name: Update secrets.yml.template
        entry: python scripts/update_template.py
        language: python
        stages: [pre-commit]
        additional_dependencies: [pyyaml]
